config/routes.rb
Manfer::Application.routes.draw do
  scope "/:locale", :constraints => {:locale => /es|gl/} do
    get "home" => "company#home", :as => "company_home"
    get "services" => "company#services", :as => "company_services"
    get "links" => "company#links", :as => "company_links"
    get "contact" => "company#contact", :as => "company_contact"
    root :to => 'company#home'

  end
  root :to => 'company#home'
  resources :contacts, only: [:create]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :interest, :message, :name

  validates :email,
            presence: true

  validates :message,
            presence: true

  after_create :deliver_email

  def self.interest_values
    [[I18n.t("contact.interest.comunidades"), "comunidades"],[I18n.t("contact.interest.seguros"), "seguros"]]
  end

  private

  def deliver_email
    ContactMailer.contact_customer(self).deliver!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    {
        :locale => I18n.locale
    }
  end

end

app/controllers/company_controller.rb
class CompanyController < ApplicationController

  def home
   set_tab [ :home]
  end

  def services
    set_tab [:services]
  end

  def links
    set_tab [:links]
  end

  def contact
    set_tab [:contact_mailer]
    @contact = Contact.new params[:contact_mailer]
  end

end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base

  def create
    create! { [:company, :contact] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def locale_flag(locale)
    content_tag :li,
                :class => "locale #{'current_locale' if I18n.locale == locale}",
                :style => I18n.locale == locale ? "" : "display:none" do
      link_to image_tag("flags/#{locale}.png"), :locale => locale
    end
  end

  def render_flash
    flash_class = {notice: "alert-success", alert: "alert-error"}

    flash.map do |name, msg|
      content_tag :div,
                  class: "alert #{flash_class[name]}", 'data-alert' => 'true' do

        content = []
        content << link_to('&times;'.html_safe, '#', class: 'close', :"data-dismiss" => 'alert')
        content << msg
        content.join('').html_safe
      end
    end.join('').html_safe
  end

  # Provides a link styled as a button.
  #
  # @param [String] anchor The anchor for the link
  # @param [String] URL The address to link to
  # @param [Hash] options The options for link_to
  # @return [String] the link with the needed styles
  def button_link_to anchor, url, options = {}
    klazz = options.delete(:class)

    if klazz.present?
      options[:class] = "btn #{klazz}"
    else
      options[:class] = "btn"
    end

    link_to anchor, url, options
  end

  # Draws an icon which shows a popover on hover
  # @param [String] content The content of the popover
  # @param [String] title The title on the popover
  def popover_info_icon(content, title, options={})
    options[:placement]||= "right"
    formated_content = content_tag :div, simple_format(content), class: 'left'
    formated_title = content_tag :div, title, class: 'left'

    icon = content_tag :i, nil,
                       'class' => 'icon-info-sign',
                       'data-content' => "#{formated_content}",
                       'data-original-title' => "#{formated_title}",
                       'data-placement' => options[:placement],
                       'rel' => 'popover'

    icon
  end

  def content_with_icon(content, klazz, color = nil)
      icon_class = "icon-#{klazz}"
      icon_class << " icon-white" if color == :white
      icon = content_tag :i, nil, class: icon_class

      (icon + " #{content}".html_safe)
  end
end

app/helpers/company_helper.rb
module CompanyHelper
  def comunity_services_traductor(service)
    return t(".comunity."+service)
  end

  def insurances_services_traductor(service)
    return t(".insurance."+service)
  end

  def links_interesting_traductor(link)
    return t(".link_interesting." + link)
  end

  def links_city_traductor(link)
    return t(".link_city."+link)
  end
end

app/views/application/_footer.html.haml
%hr.space
.footer
  .container
    .row
      .span4
        %h3= content_with_icon t("footer.address"), "pencil", :white
        %p C/ Castelao 10, 3º Izq
        %p VILAGARCÍA DE AROUSA - 36600 PONTEVEDRA
        %p= "<strong>Tfn.</strong>: 986.186.463 <strong>Fax:</strong> 986.189.882".html_safe
      .span4
        %h3= content_with_icon t("footer.email"), "envelope", :white
        %p administraciondefincas@manfercomunidades.com
      .span4
        %h3= content_with_icon t("footer.copyright.title"), "search", :white
        %p= t("footer.copyright.content")

app/views/application/_languages.haml
%ul#available_languages.nav.pull-right
  - I18n.available_locales.each do |locale|
    = locale_flag locale

app/views/application/_menu.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to image_tag("logo.jpeg", alt: "Manfer Comunidades"), company_home_path, class: "brand"
      .nav-collapse
        = tabs_tag open_tabs: {class: 'nav'}, builder: MenuBuilder do |tab|
          = tab.home company_home_path
          = tab.services company_services_path
          = tab.links company_links_path
          = tab.contact company_contact_path
      = render "languages"
      %p#colegiado_info= t("header.colegiado")

app/views/company/_customers_manage_community.html.haml
.span4
  .well.pagination-centered
    %h2.label.label-important= t("customer_link.title").upcase
    %p=  t "customer_link.content"
    = link_to t("enter"), "http://www.netfincasweb.com/acceder-despacho.php",
      class: "btn btn-large", target: :_blank
    %hr
    = image_tag "gestion_hogar.jpeg"

app/views/company/contact.html.haml
.container
  .row
    = simple_form_for @contact, html: {class: "span7 form-horizontal well"} do |f|
      %fieldset
        %h1= t ".title"
        .span3
          = f.input :name, placeholder: "ej: Juan Peleteiro"
        .span3
          = f.input :email, placeholder: "ej: juan.peleteiro@gmail.com"
        .span3
          = f.input :message, as: "text", placeholder: "blah blah", cols: 80;
        .span3
          = f.input :interest, collection: Contact.interest_values, include_blank: false
          %br
          = f.submit t(".form.submit") , class: "btn btn-large"

    .well.span4
      %p= content_with_icon t(".text"), "pencil", :white

    .well.span4.pagination-centered
      = image_tag "qr.png"

app/views/company/home.html.haml
- content_for :meta_title do
  = "#{ t(".title") }"

%br
.container
  .row
    .span12
      .paginate-center
        %h2= t(".title")
        .royalSlider.rsDefault
          .sliderItem
            =image_tag "ejemplos/panoramica.jpg", class: "rsImg", alt: "una descripicon cualquiera"
            #block_1_1.rsABlock{ "data" => { "move-effect" => "left", "speed" => "3000", "delay" => "500" }}
              %br
              %br
              %br
              %br
              %br
              %p.white= raw t(".slider.first")

          .sliderItem
            =image_tag "ejemplos/vilagarcia.jpg", class: "rsImg"
            #block_2_1.rsABlock{ "data" => { "move-effect" => "right", "speed" => "3000", "delay" => "500" }}
              %p.white= raw t(".slider.second")


  %br
    %br
  .row
    .span8

      %h2= t(".main.title")
      %p= raw t(".main.content")

    = render "customers_manage_community"

app/views/company/links.html.haml
- content_for :title do t(".title") end

.container
  .row
    .span8
      .well
        %h1= t(".link_interesting.link_interesting_title")
        %ul
          %li
            %span= t ".link_interesting.link_neighboor_comunity"
            %span= link_to t(".visit"), "http://www.euroresidentes.com/vivienda/comunidades_de_vecinos/" , class: "label label-info", target: :_blank
          %li
            %span= t ".link_interesting.link_home_dictionary"
            %span= link_to t(".visit"), "http://www.euroresidentes.com/vivienda/hipotecas/diccionario/index_2.htm" , class: "label label-info", target: :_blank
          %li
            %span= t ".link_interesting.link_coadga"
            %span= link_to t(".visit"), "http://www.coafga.org/" , class: "label label-info", target: :_blank
          %li
            %span= t ".link_interesting.link_village"
            %span= link_to t(".visit"), "http://www.vilagarcia.es/" , class: "label label-info", target: :_blank
          %li
            %span= t ".link_interesting.link_panoramics"
            %span= link_to t(".visit"), "http://www.descubregalicia.com/" , class: "label label-info", target: :_blank
          %li
            %span= t ".link_interesting.link_phones"
            %span= link_to t(".visit"), "http://www.turvilagarcia.com/telefono_interes.asp" , class: "label label-info", target: :_blank
    = render "customers_manage_community"

app/views/company/services.html.haml
- content_for :title do t(".title") end

- comunity_services_list = ["fact_monthly","at_breakdown","web_access",
"cel_assembly","ad_legal","claim_defaulter","custom_attention",
"ask_subvention","budgets","maintenance"]

- insurances_services_list = ["comunity","home","life","car",
"boat","decennial","house","burial"]

.container
  .row
    .span8
      .well
        %h2= t(".comunity.title_comunity")
        %ul
        -comunity_services_list.each do |service|
          %li= comunity_services_traductor(service)
        %br
        %br
        %br

    .span4
      .well.pagination-centered
        %h2.label.label-important= t(".quote.title").upcase
        %p=  t ".quote.content"
        = link_to t(".quote.submit"),company_contact_path , class: "btn btn-large"
        %hr
        = image_tag "agreement.jpeg"
  .row
    .span12
      .well.clearfix
        .span4
          %h2= t(".insurance.title")
          %ul
          -insurances_services_list.each do |service|
            %li= insurances_services_traductor(service)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{yield :meta_title} | Manfer Comunidades

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"

    = csrf_meta_tags

  %body{class: "#{controller_path.split("/").join(" ")}"}


    = render 'menu'

    %br

    .subbar
      .container
        .row
          .span12
            = flash[:message]

            %h1= yield :title

    .container
      -#= render 'submenu'
      = render_flash
      = yield

    = render 'footer'